mm, vmevent: vmevent_fd is conditional on CONFIG_VMEVENT
The vmevent_fd syscall is declared but not defined without CONFIG_VMEVENT,
so make it conditional to avoid the following link error:

	arch/x86/built-in.o:(.rodata+0xdb0): undefined reference to `sys_vmevent_fd'

Signed-off-by: David Rientjes <rientjes@google.com>
Signed-off-by: Pekka Enberg <penberg@kernel.org>